### ISSUE TITLE
Needs Tutorial

### ISSUE THREAD

**Issue by vendza** [fe80Grau/ytdlp2STRM#27]
How do I get this program to work, I have tried for 4 days and no bueno, could you be a liitle bit more specific with the readme and actually leave a good example for the json files. This is a great idea I want to use it but am not able to. Please break it down Barney style.

**Comment by fe80Grau** [comment]
Hello @vendza , the user guide is in the README that you can view in the root of the project right here on Github, perhaps it is somewhat extensive and technical, but I think that knowing how to run python scripts is enough knowledge to make this work.

I don't know if you are under Linux or Windows, maybe you are trying to implement it in Docker... give me a little more information and I will be able to help you, tell me, after following the steps in your operating system, if you go to the browser and access the url http ://localhost:5000/ can you see the interface or do you get an error?

If what you are looking for is to generate the STRM files manually, I also talk about it in the README section CLI.PY, search for "build strms manually" with CTRL+F if you can't find it, there I describe how to generate the files if you don't want wait for CRON by default.

Remind you that it is a script as a service, it must run in the background constantly for it to work. Make sure you clearly indicate the directories where you are going to store the strm's in each plugin, you can do it from the web interface.

I can't blindly think of anything else that could be happening to you, unless you really aren't understanding anything, in which case tell me what your problem is and together we will make it work.

Cheers.

**Comment by vendza** [comment]
I think the problem is the docker implementation and the prerequisites
required. I am running on unraid using your docker which won't run at all.
Maybe submit the yaml file to unraid for inclusion into their appstore. And
maybe have a better example config.json for the plugins.

**Comment by fe80Grau** [comment]
Pull last commit or check this issue https://github.com/fe80Grau/ytdlp2STRM/issues/26
