### ISSUE TITLE
ytdlp2strm is downloading streams from crunchyroll instead of streaming

### ISSUE THREAD

**Issue by s3tupw1zard** [fe80Grau/ytdlp2STRM#43]
Hello,

When I try to stream a Crunchyroll Video using this tool, it downloads the episode requested instead of streaming it.

Is there a setting to completely disable downloading for crunchyroll?

I've already set it to direct.

**Comment by fe80Grau** [comment]
Hello, it's a shame but since the last update of the Crunchyroll endpoints, it only shows Dash routes for the separate audio and video, there is no longer an endpoint with the direct content. Work started at https://github.com/fe80Grau/ytdlp2STRM/issues/36#issuecomment-2045858376

I've also not been able to remux in RAM and transmit in real time as the final flow is built, therefore the only option is to download as a temporary file. In ./config/config.json there is a new parameter called ytdlp2strm_temp_file_duration, this has the duration of a temporary file in seconds, by default 86400s / 24h. This means that a temporary file (located in ./temp) that is older than 86400 seconds will be automatically deleted.
